markdown_extensions:
  - 'meta'
  - 'pymdownx.mark'
  - 'pymdownx.magiclink'
  - 'pymdownx.emoji'
  - 'pymdownx.keys'
  - 'def_list'
  - 'admonition'
  - codehilite:
      linenums: true
      use_pygments: true

nav:
  - Home: 'index.md'
  - はじめに:
    - vagrantとは: 'intro/vagrant.md'
    - インストール: 'intro/install.md'
  - 使ってみる:
    - 準備: 'how_to_use/preparation.md'
    - VM作成: 'how_to_use/create.md'
    - OS一覧: 'how_to_use/box.md'
  - Vagrantfileの活用:
    - Vagrantfileとは: 'vagrantfile/vagrantfile.md'
    - ネットワーク: 'vagrantfile/network.md'
    - ファイル共有: 'vagrantfile/sync.md'
    - プロビジョニング: 'vagrantfile/provision.md'
    - まとめ: 'vagrantfile/summary.md'

site_name: 'Vagrant Introduction'

theme:
  feature:
    tabs: true
  language: 'ja'
  name: 'material'
  palette:
    accent: 'Ocean'
    primary: 'blue'
